[workspace]
resolver = "2"
members = [
    "components/gate-ip-name-lookup",
    "components/gate-types",
    "components/gate",
    "components/latch-cidr-bind",
    "components/latch-cidr-egress",
    "components/latch-cidr-ingress",
    "components/latch-cidr",
    "components/latch-defer-all",
    "components/latch-delegate-tcp",
    "components/latch-delegate-udp",
    "components/latch-deny-all",
    "components/latch-deny-bind",
    "components/latch-deny-connect-unless-lookup-address",
    "components/latch-deny-connect",
    "components/latch-deny-ipv4",
    "components/latch-deny-ipv6",
    "components/latch-deny-random",
    "components/latch-deny-tcp",
    "components/latch-deny-udp",
    "components/latch-dry-run",
    "components/latch-ip-name-lookup-glob",
    "components/latch-n2",
    "components/latch-n3",
    "components/latch-n4",
    "components/latch-n5",
    "components/latch-trace",
    "components/test-latch-deny-private-networks",
    "components/trace-ip-name-lookup",
    "components/trace-types",
    "components/trace",
    "crates/*",
]

[workspace.dependencies]
componentized-rt = { path = "./crates/componentized-rt" }
heck = "0.5"
ipnet = "2"
latch-cidr = { path = "./crates/latch-cidr" }
sockets-latch = { path = "./crates/sockets-latch" }
sockets-latch-n = { path = "./crates/sockets-latch-n" }
test-harness = { path = "./crates/test-harness" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "sync", "time"] }
wac-graph = "0.12"
wasmtime = { version = "49", features = ["component-model-async"] }
wasmtime-wasi = { version = "49", features = ["p3"] }
wit-bindgen = { version = "0.62.0", features = ["async-spawn"] }
